# Generated by Django 5.2.8 on 2025-12-04 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tasks_created', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Minutes')),
                ('completion_rate', models.FloatField(default=0.0)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_voice_reminders', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.IntegerField(default=5)),
                ('work_start_time', models.TimeField(default='09:00')),
                ('work_end_time', models.TimeField(default='17:00')),
                ('preferred_task_duration', models.IntegerField(default=30)),
                ('ai_auto_breakdown', models.BooleanField(default=True)),
                ('ai_scheduling_suggestions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['-date', 'time', 'order']},
        ),
        migrations.AddField(
            model_name='routine',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('health', 'Health'), ('study', 'Study'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='routine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='estimated_duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='routine',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routine',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='manager.routine'),
        ),
        migrations.AddField(
            model_name='routine',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='routine',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routine',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
        migrations.AddField(
            model_name='routine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='repeat_type',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['user', 'date', 'status'], name='manager_rou_user_id_8f9652_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['user', 'is_completed'], name='manager_rou_user_id_5cf1eb_idx'),
        ),
        migrations.AddField(
            model_name='productivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasknote',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='manager.routine'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productivitylog',
            unique_together={('user', 'date')},
        ),
    ]
