# Generated by Django 5.2.8 on 2025-12-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_routine_options_routine_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
